# site settings
title: dlals335 Portfolio
subtitle: AI & Real-time System Developer
email: dlals335@gmail.com
description: Fit-Boss 프로젝트 팀장 | AI 모델 경량화 및 실시간 최적화 전문가
baseurl: ""
url: "https://dlals335.github.io"
author: dlals335

# homepage tiles
tiles-source: pages
tiles-count: 6

# social settings
socials:
  GitHub: https://github.com/dlals335
  LinkedIn: 
  Instagram: 
  Twitter: 

# build settings
markdown: kramdown
sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
